#coding=utf-8
from LoginPage import *
import random
class SGshentubiao(Page):
#######################################################       平面图审图表     ##########################################
    url='/'
    def sg_shentubiao (self,shenheren,changliang):
        LoginPage(self.dr).Login_action(shenheren, "290089974")
        Daiban(self.dr).daiban(changliang)
        sleep(2)
        if (self.dr.find_element_by_xpath('(//div[@class="panel-header"])[4]')).text == u'局部整改':
            j = range(1, 25)
            for i in j:
                i = bytes(i)
                self.by_xpath_y(i)
                x = random.randrange(100, 1001, 50)
                self.by_xpath_z(i, x)
            #
            # self.by_xpath_y("1")
            # self.by_xpath_s("(//input[@type='text'])[1]", "888")
            # self.by_xpath_y("2")
            # self.by_xpath_s("(//input[@type='text'])[2]", "8")
            # self.by_xpath_y("3")
            # self.by_xpath_s("(//input[@type='text'])[3]", "8")
            # self.by_xpath_y("4")
            # self.by_xpath_s("(//input[@type='text'])[4]", "8")
            # self.by_xpath_y("5")
            # self.by_xpath_s("(//input[@type='text'])[5]", "88")
            # self.by_xpath_y("6")
            # self.by_xpath_s("(//input[@type='text'])[6]", "8")
            # self.by_xpath_y("7")
            # self.by_xpath_s("(//input[@type='text'])[7]", "8")
            # self.by_xpath_y("8")
            # self.by_xpath_s("(//input[@type='text'])[8]", "8")
            # self.by_xpath_y("9")
            # self.by_xpath_s("(//input[@type='text'])[9]", "8")
            # self.by_xpath_y("10")
            # self.by_xpath_s("(//input[@type='text'])[10]", "8")
            # self.by_xpath_y("11")
            # self.by_xpath_s("(//input[@type='text'])[11]", "8")
            # self.by_xpath_y("12")
            # self.by_xpath_s("(//input[@type='text'])[12]", "8")
            # self.by_xpath_y("13")
            # self.by_xpath_s("(//input[@type='text'])[13]", "8")
            # self.by_xpath_y("14")
            # self.by_xpath_s("(//input[@type='text'])[14]", "8")
            # self.by_xpath_y("15")
            # self.by_xpath_s("(//input[@type='text'])[15]", "8")
            # self.by_xpath_y("16")
            # self.by_xpath_s("(//input[@type='text'])[16]", "88")
            # self.by_xpath_y("17")
            # self.by_xpath_s("(//input[@type='text'])[17]", "88")
            # self.by_xpath_y("18")
            # self.by_xpath_s("(//input[@type='text'])[18]", "88")
            # self.by_xpath_y("19")
            # self.by_xpath_s("(//input[@type='text'])[19]", "88")
            # self.by_xpath_y("20")
            # self.by_xpath_s("(//input[@type='text'])[20]", "88")
            # self.by_xpath_y("21")
            # self.by_xpath_s("(//input[@type='text'])[21]", "88")
            # self.by_xpath_y("22")
            # self.by_xpath_s("(//input[@type='text'])[22]", "8")
            # self.by_xpath_y("23")
            # self.by_xpath_s("(//input[@type='text'])[23]", "8")
            # self.by_xpath_y("24")
            # self.by_xpath_s("(//input[@type='text'])[24]", "8")
            # self.by_css('[class="el-switch__label el-switch__label--right"]')
            # self.by_xpath("(//span[@class='el-radio__inner'])[1]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[3]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[5]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[7]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[9]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[11]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[13]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[15]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[17]")
        elif (self.dr.find_element_by_xpath('(//div[@class="panel-header"])[5]')).text == u'电器面积':
            j = range(1, 20)
            for i in j:
                i = bytes(i)
                self.by_xpath_y(i)
                x = random.randrange(100, 1001, 50)
                self.by_xpath_z(i, x)
            # self.by_xpath_y("1")
            # self.by_xpath_s("(//input[@type='text'])[1]", "88")
            # self.by_xpath_y("2")
            # self.by_xpath_s("(//input[@type='text'])[2]", "88")
            # self.by_xpath_y("3")
            # self.by_xpath_s("(//input[@type='text'])[3]", "8")
            # self.by_xpath_y("4")
            # self.by_xpath_s("(//input[@type='text'])[4]", "8")
            # self.by_xpath_y("5")
            # self.by_xpath_s("(//input[@type='text'])[5]", "8")
            # self.by_xpath_y("6")
            # self.by_xpath_s("(//input[@type='text'])[6]", "8")
            # self.by_xpath_y("7")
            # self.by_xpath_s("(//input[@type='text'])[7]", "8")
            # self.by_xpath_y("8")
            # self.by_xpath_s("(//input[@type='text'])[8]", "8")
            # self.by_xpath_y("9")
            # self.by_xpath_s("(//input[@type='text'])[9]", "8")
            # self.by_xpath_y("10")
            # self.by_xpath_s("(//input[@type='text'])[10]", "8")
            # self.by_xpath_y("11")
            # self.by_xpath_s("(//input[@type='text'])[11]", "88")
            # self.by_xpath_y("12")
            # self.by_xpath_s("(//input[@type='text'])[12]", "88")
            # self.by_xpath_y("13")
            # self.by_xpath_s("(//input[@type='text'])[13]", "88")
            # self.by_xpath_y("14")
            # self.by_xpath_s("(//input[@type='text'])[14]", "88")
            # self.by_xpath_y("15")
            # self.by_xpath_s("(//input[@type='text'])[15]", "88")
            # self.by_xpath_y("16")
            # self.by_xpath_s("(//input[@type='text'])[16]", "352")
            # self.by_xpath_y("17")
            # self.by_xpath_s("(//input[@type='text'])[17]", "8")
            # self.by_xpath_y("18")
            # self.by_xpath_s("(//input[@type='text'])[18]", "8")
            # self.by_xpath_y("19")
            # self.by_xpath_s("(//input[@type='text'])[19]", "8")
            # self.by_css('[class="el-switch__label el-switch__label--right"]')
            # self.by_xpath("(//span[@class='el-radio__inner'])[1]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[3]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[5]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[7]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[9]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[11]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[13]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[15]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[17]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[19]")
        elif (self.dr.find_element_by_xpath('(//div[@class="panel-header"])[5]')).text == u'平面图公共面积审核':
            j = range(1, 16)
            for i in j:
                i = bytes(i)
                self.by_xpath_y(i)
                x = random.randrange(100, 1001, 50)
                self.by_xpath_z(i, x)
            # self.by_xpath_y("1")
            # self.by_xpath_s("(//input[@type='text'])[1]", "888")
            # self.by_xpath_y("2")
            # self.by_xpath_s("(//input[@type='text'])[2]", "8")
            # self.by_xpath_y("3")
            # self.by_xpath_s("(//input[@type='text'])[3]", "8")
            # self.by_xpath_y("4")
            # self.by_xpath_s("(//input[@type='text'])[4]", "8")
            # self.by_xpath_y("5")
            # self.by_xpath_s("(//input[@type='text'])[5]", "8")
            # self.by_xpath_y("6")
            # self.by_xpath_s("(//input[@type='text'])[6]", "8")
            # self.by_xpath_y("7")
            # self.by_xpath_s("(//input[@type='text'])[7]", "88")
            # self.by_xpath_y("8")
            # self.by_xpath_s("(//input[@type='text'])[8]", "88")
            # self.by_xpath_y("9")
            # self.by_xpath_s("(//input[@type='text'])[9]", "88")
            # self.by_xpath_y("10")
            # self.by_xpath_s("(//input[@type='text'])[10]", "88")
            # self.by_xpath_y("11")
            # self.by_xpath_s("(//input[@type='text'])[11]", "88")
            # self.by_xpath_y("12")
            # self.by_xpath_s("(//input[@type='text'])[12]", "8")
            # self.by_xpath_y("13")
            # self.by_xpath_s("(//input[@type='text'])[13]", "8")
            # self.by_xpath_y("14")
            # self.by_xpath_s("(//input[@type='text'])[14]", "8")
            # self.by_xpath_y("15")
            # self.by_xpath_s("(//input[@type='text'])[15]", "8")
            # self.by_css('[class="el-switch__label el-switch__label--right"]')
            # self.by_xpath("(//span[@class='el-radio__inner'])[1]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[3]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[5]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[7]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[9]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[11]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[13]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[15]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[17]")
        else:
            j = range(1, 17)
            for i in j:
                i = bytes(i)
                self.by_xpath_y(i)
                x = random.randrange(100, 1001, 50)
                self.by_xpath_z(i, x)
            # self.by_xpath_y("1")
            # self.by_xpath_s("(//input[@type='text'])[1]", "888")
            # self.by_xpath_y("2")
            # self.by_xpath_s("(//input[@type='text'])[2]", "8")
            # self.by_xpath_y("3")
            # self.by_xpath_s("(//input[@type='text'])[3]", "8")
            # self.by_xpath_y("4")
            # self.by_xpath_s("(//input[@type='text'])[4]", "8")
            # self.by_xpath_y("5")
            # self.by_xpath_s("(//input[@type='text'])[5]", "8")
            # self.by_xpath_y("6")
            # self.by_xpath_s("(//input[@type='text'])[6]", "8")
            # self.by_xpath_y("7")
            # self.by_xpath_s("(//input[@type='text'])[7]", "88")
            # self.by_xpath_y("8")
            # self.by_xpath_s("(//input[@type='text'])[8]", "88")
            # self.by_xpath_y("9")
            # self.by_xpath_s("(//input[@type='text'])[9]", "88")
            # self.by_xpath_y("10")
            # self.by_xpath_s("(//input[@type='text'])[10]", "88")
            # self.by_xpath_y("11")
            # self.by_xpath_s("(//input[@type='text'])[11]", "88")
            # self.by_xpath_y("12")
            # self.by_xpath_s("(//input[@type='text'])[12]", "888")
            # self.by_xpath_y("13")
            # self.by_xpath_s("(//input[@type='text'])[13]", "8")
            # self.by_xpath_y("14")
            # self.by_xpath_s("(//input[@type='text'])[14]", "8")
            # self.by_xpath_y("15")
            # self.by_xpath_s("(//input[@type='text'])[15]", "8")
            # self.by_xpath_y("16")
            # self.by_xpath_s("(//input[@type='text'])[16]", "8")
            # self.by_xpath("(//span[@class='el-radio__inner'])[1]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[3]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[5]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[7]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[9]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[11]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[13]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[15]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[17]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[19]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[21]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[23]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[25]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[27]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[29]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[31]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[33]")
            # self.by_xpath("(//span[@class='el-radio__inner'])[35]")
        # self.by_css('button[class="el-button el-button--primary"]')
        # sleep(2)
        # self.by_css("a[href='javascript:void(0)']")