#coding=utf-8
import time
from LoginPage import *
from model import function
class Xzsc(Page):
    def xzsc(self,shenheren,password):
        xpath="1"
        xx=(u"考试法人"+time.strftime("%y.%m.%d.%H_%M"))
        yy=(u"考试商场"+time.strftime("%y%m%d%H%M"))    #商场名称
        mdmc=(u"考试门店"+time.strftime("%y.%m.%d.%H_%M"))
        LoginPage(self.dr).Login_action(shenheren, password)
        print u'商场名称：',yy
        print u'门店名称：',mdmc
        self.by_xpath('//*[text()="商场管理"]')
        sleep(1.8)
        if shenheren=="OP.02349":
            self.by_xpath('//*[text()="集成家居经销一部"]')
            sleep(1)
            self.by_xpath('//*[text()="E1线"]')
        elif shenheren=="OP.14556":
            self.by_xpath('//*[text()="橱柜经销一部"]')
            sleep(1)
            self.by_xpath('//*[text()="A2"]')
        elif shenheren=='OP.06073':
            self.by_xpath('//*[text()="欧铂丽经销部"]')
            sleep(1)
            self.by_xpath('//*[text()="Y1"]')
        else:
            self.by_xpath('//*[text()="欧派大家居营销线"]')
            sleep(1)
            self.by_xpath('//*[text()="大家居临时线别"]')
        self.by_xpath('//*[text()="新增品类/商场"]')
        sleep(1)
        self.by_xpath('//*[text()="新增商场"]')
        sleep(1)
        if shenheren == "OP.41326":
            self.by_xpath_x('(//*[@class="el-input__icon el-icon-caret-top"])[1]')
            sleep(0.5)
            self.by_xpath('(//*[@class="el-scrollbar"])[10]/div/ul/li[2]')
            self.by_xpath('(//*[@class="el-scrollbar"])[10]/div/ul/li[3]')
            self.by_xpath('(//*[@class="el-scrollbar"])[10]/div/ul/li[4]')
            self.by_xpath('(//*[@class="el-scrollbar"])[10]/div/ul/li[5]')
            self.by_xpath('(//*[@class="el-scrollbar"])[10]/div/ul/li[6]')
            sleep(1)
            self.by_css('[class="el-input__icon el-icon-caret-top is-reverse"]')
        elif shenheren=='OP.06073':
            self.by_xpath('(//*[@class="el-input__icon el-icon-caret-top"])[1]')
            sleep(0.5)
            self.by_xpath('(//*[@class="el-scrollbar"])[10]/div/ul/li[2]')
            sleep(1)
            self.by_css('[class="el-input__icon el-icon-caret-top is-reverse"]')
        self.by_xpath_z("2",xx)
        self.by_xpath_z("3","555555555555555555")
        self.by_xpath_z("4","13533333333")
        self.by_xpath_z("6",u"白云新镇庄1号")
        self.by_xpath_z("7","555555")
        self.by_xpath_z("8",yy)
        self.by_xpath_x("9")
        sleep(0.5)
        self.by_xpath('//*[text()="五级级别"]')
        self.by_xpath_x("10")
        sleep(0.5)
        self.by_xpath('//*[text()="有效"]')
        self.by_xpath_x("11")
        sleep(0.5)
        self.by_xpath('//*[text()="橱衣综合经销商"]')
        self.by_xpath_x("12")
        sleep(0.5)
        self.by_xpath('//*[text()="今天"]')
        self.by_xpath_x("13")
        sleep(0.5)
        self.by_xpath('//*[text()="转正商场"]')
        self.by_xpath_z("14","555")
        self.by_xpath_z("15","0.55")
        '''
        self.by_xpath_b("1")
        sleep(0.5)
        self.by_xpath_b("11")
        self.by_xpath_b("21")
        sleep(0.5)
        self.by_xpath_b("2")
        self.by_xpath_b("21")
        sleep(0.5)
        self.by_xpath_b("3")
        self.by_xpath_b("21")
        sleep(0.5)
        self.by_xpath_b("4")
        self.by_xpath_b("21")
        sleep(0.5)
        self.by_xpath_b("5")
        self.by_xpath_b("21")
        sleep(0.5)
        self.by_xpath_b("6")
        self.by_xpath_b("21")
        sleep(0.5)
        self.by_xpath_b("7")
        self.by_xpath_b("21")
        '''
        sleep(0.5)
        self.by_xpath('(.//*[@class="el-radio__inner"])[2]')
        self.by_xpath('(.//*[@class="el-radio__inner"])[4]')
        self.by_xpath_z("23","431700")
        self.by_xpath_x("24")
        sleep(0.5)
        self.by_xpath('//*[text()="广东省"]')
        self.by_xpath_x("25")
        sleep(0.5)
        self.by_xpath('//*[text()="广州市"]')
        self.by_xpath_x("26")
        sleep(0.5)
        self.by_xpath('//*[text()="白云区"]')
        self.by_xpath_x("27")
        sleep(0.5)
        self.by_xpath('//*[text()="江高镇"]')
        # jietu_name = yy +  u"截图_1.png"
        # function.insert_img(self.dr, jietu_name)
        self.by_xpath_z("28",u'广花三路366号欧派北区')
        self.by_xpath_z("29",u'小武哥')
        self.by_xpath_z("30",u'55555555555')
        self.by_xpath_z("31",u'广花三路366号欧派北区')
        self.by_xpath_s('(//*[@type="textarea"])[1]',u'店长有点懒')
        # jietu_name = yy +  u"截图_2.png"
        # function.insert_img(self.dr, jietu_name)
        self.by_xpath_x("35")
        sleep(0.5)
        self.by_xpath('(//*[text()="今天"])[2]')
        self.by_xpath_x("36")
        sleep(1)
        self.by_xpath('(//*[text()="今天"])[3]')
        self.by_xpath_s('(//*[@type="textarea"])[2]',u"系统管理员长得非常帅也非常漂亮")
        self.by_xpath_b("8")
        sleep(4.5)
        self.by_xpath('(//*[contains(text(),"继续")])[2]')   #####选取消继续编辑
        sleep(1)
        # self.by_css_s('[placeholder="请输入快递地址"]',u'A栋')
        # jietu_name = yy +  u"截图_3.png"
        # function.insert_img(self.dr, jietu_name)
        sleep(3.5)
        self.by_xpath('//*[text()="商场店面信息"]')
        self.by_xpath('//*[contains(text(),"新增店面")]')
        sleep(0.5)
        self.by_xpath_x('42')
        sleep(1)
        if shenheren=="OP.02349":
            self.by_xpath('//*[text()="欧派-集成家居"]')
        elif shenheren=="OP.14556":
            self.by_xpath('//*[text()="欧派-橱柜"]')
        elif shenheren=='OP.06073':
            self.by_xpath('//*[text()="欧铂丽-集成家居"]')
            self.by_xpath('//*[text()="欧铂丽-橱柜"]')
        else:
            self.by_xpath('//*[text()="欧派-集成家居"]')
            self.by_xpath('//*[text()="欧派-卫浴"]')
            self.by_xpath('//*[text()="欧派-大家居"]')
            self.by_xpath('//*[text()="欧派-墙饰"]')
            self.by_xpath('//*[text()="欧派-木门"]')
            self.by_xpath('//*[text()="欧派-橱柜"]')
        self.by_xpath_x('43')
        sleep(0.8)
        self.by_xpath('(//*[text()="窗口店"])[2]')
        self.by_xpath_x('44')
        sleep(0.5)
        self.by_xpath('(//*[text()="家装店"])[3]')
        self.by_xpath_x('45')
        sleep(0.5)
        self.by_xpath('//*[text()="独立店"]')
        self.by_xpath_x('57')
        sleep(0.5)
        self.by_xpath('//*[text()="今天"]')
        self.by_xpath_x('58')
        sleep(0.5)
        self.by_xpath('(//*[text()="局部整改"])[1]')
        sleep(0.5)
        self.by_xpath_x('61')
        sleep(0.5)
        self.by_xpath('//*[text()="正常"]')
        self.by_xpath_x('63')
        sleep(0.5)
        self.by_xpath('(//*[text()="广东省"])[2]')
        self.by_xpath_x('64')
        sleep(0.5)
        self.by_xpath('(//*[text()="广州市"])[2]')
        sleep(0.5)
        js = "window.scrollTo(100,450)"
        self.dr.execute_script(js)
        self.by_xpath_x('65')
        sleep(0.5)
        self.by_xpath('(//*[text()="白云区"])[2]')
        self.by_xpath_x('66')
        sleep(0.5)
        self.by_xpath('(//*[text()="三元里街道"])[2]')
        self.by_xpath_z('40',mdmc)
        self.by_xpath_z('41','555')
        self.by_xpath_z('46','15555555555')
        self.by_xpath_z('47','020258835')
        self.by_xpath_z('48','431700')
        self.by_xpath_z('49','200')
        self.by_xpath_z('50','200')
        self.by_xpath_z('51','200')
        self.by_xpath_z('52','200')
        self.by_xpath_z('53','200')
        self.by_xpath_z('54','200')
        self.by_xpath_z('55','200')
        self.by_xpath_z('56','200')
        # self.by_xpath_z('59',u'陈大大')
        self.by_xpath_z('60',u'爱拼才会赢')
        self.by_xpath_z('62',u'拼太狠了')
        self.by_xpath_z('67',u'广花三路366号欧派北区')
        self.by_css('[class="upload-box"]')
        os.system("D:\\upfile.exe")
        sleep(2)
        # jietu_name = yy +  u"门店数据截图.png"
        # function.insert_img(self.dr, jietu_name)
        self.by_xpath('(//*[text()="保存"])[3]')
        sleep(2.5)
        self.by_xpath('(//*[text()="商场管理"])[1]')
        sleep(1.8)
        if shenheren=="OP.02349":
            self.by_xpath('//*[text()="集成家居经销一部"]')
            sleep(1)
            self.by_xpath('//*[text()="E1线"]')
        elif shenheren=="OP.14556":
            self.by_xpath('//*[text()="橱柜经销一部"]')
            sleep(1)
            self.by_xpath('//*[text()="A2"]')
        elif shenheren=='OP.06073':
            self.by_xpath('//*[text()="欧铂丽经销部"]')
            sleep(1)
            self.by_xpath('//*[text()="X1"]')
        else:
            self.by_xpath('//*[text()="欧派大家居营销线"]')
            sleep(1)
            self.by_xpath('//*[text()="大家居临时线别"]')
        self.by_xpath('//*[text()="新增品类/商场"]')
        self.by_xpath_z("1",yy)
        sleep(2)
        self.by_xpath('//*[text()="查询"]')
        sleep(1)
        op=(self.dr.find_element_by_xpath('(//*[@class="el-table__row"])[1]/td[4]')).text
        print u'商场编号：',op
        sleep(2)
        self.by_css('span[class="fa fa-power-off"]')

    def xzmd(self,shenheren):
        yy=u"CSSC07.11.19_38"
        mdmc=(u"门店CS"+time.strftime("%m.%d.%H_%M"))
        LoginPage(self.dr).Login_action(shenheren,"111111")
        sleep(0.5)
        self.by_xpath('//*[text()="商场管理"]')
        sleep(0.5)
        self.by_css_s('input[placeholder="搜索代理商名称/商场名称/编码"]',yy)
        self.by_xpath('//*[text()="搜索"]')
        sleep(0.5)
        self.by_xpath('(//*[text()="编辑"])[1]')
        sleep(0.5)
        self.by_xpath('//*[text()="商场店面信息"]')
        self.by_xpath('//*[contains(text(),"新增店面")]')
        sleep(0.5)
        self.by_xpath_x('40')
        sleep(0.5)
        self.by_xpath('//*[text()="欧派-集成家居"]')
        self.by_xpath_x('41')
        sleep(0.8)
        self.by_xpath('(//*[text()="窗口店"])[2]')
        self.by_xpath_x('42')
        sleep(0.5)
        self.by_xpath('(//*[text()="家装店"])[3]')
        self.by_xpath_x('43')
        sleep(0.5)
        self.by_xpath('//*[text()="独立店"]')
        self.by_xpath_x('55')
        sleep(0.5)
        self.by_xpath('//*[text()="今天"]')
        self.by_xpath_x('56')
        sleep(0.5)
        self.by_xpath('(//*[text()="局部整改"])[1]')
        self.by_xpath_x('59')
        sleep(0.5)
        self.by_xpath('//*[text()="正常"]')
        self.by_xpath_x('61')
        sleep(0.5)
        self.by_xpath('(//*[text()="广东省"])[2]')
        self.by_xpath_x('62')
        sleep(0.5)
        self.by_xpath('(//*[text()="广州市"])[2]')
        self.by_xpath_x('63')
        sleep(0.5)
        self.by_xpath('(//*[text()="白云区"])[2]')
        self.by_xpath_x('64')
        sleep(1)
        self.by_xpath('(//*[text()="江高镇"])[2]')
        self.by_xpath_z('38',mdmc)
        self.by_xpath_z('39','555')
        self.by_xpath_z('44','15555555555')
        self.by_xpath_z('45','020258835')
        self.by_xpath_z('46','431700')
        self.by_xpath_z('47','200')
        self.by_xpath_z('48','200')
        self.by_xpath_z('49','200')
        self.by_xpath_z('50','200')
        self.by_xpath_z('51','200')
        self.by_xpath_z('52','200')
        self.by_xpath_z('53','200')
        self.by_xpath_z('54','200')
        self.by_xpath_z('57',u'陈大大')
        self.by_xpath_z('58',u'爱拼才会赢')
        self.by_xpath_z('60',u'拼太狠了')
        self.by_xpath_z('65',u'广花三路366号欧派北区')
        jietu_name = yy +  u"门店数据截图.png"
        function.insert_img(self.dr, jietu_name)
        self.by_xpath('(//*[text()="保存"])[3]')
        sleep(0.5)

    XzscPass_loc=(By.XPATH,'(//*[@class="el-table__row"])[1]/td[6]')
    XzscFail_loc = (By.ID, 'username')

    def type_xzscPass_hint(self):
        return self.find_element(*self.XzscPass_loc).text

    def type_xzscFail_hint(self):
        return self.find_element(*self.XzscFail_loc).text


